### ISSUE TITLE
关于新特性的提议

### ISSUE THREAD

**Issue by Rain-kl** [Zephyruso/zashboard#241]
是否将mihomo内核内置到docker服务中？
目前集成管理clash内核的web项目仅有openclash。其他面板只是mihomo api的集成，并不能做到像clash for windows等这种能够拉取管理订阅的功能。但是在无ui的服务器上只能通过x11 forwarding运行。
将内核添加到docker镜像中并添加控制api实现即开即用，易于管理的功能。
不知作者是否有这个意愿？

**Comment by Rain-kl** [comment]
理论上说这个功能是完全不会影响到原项目，且可以作为两个发行版本，带内核与不带内核。

**Comment by Zephyruso** [comment]
你说的这个使用docker-compose 应当就可以而不需要改动项目本身的docker?

**Comment by Zephyruso** [comment]
```
version: '3'

services:
  zashboard:
    container_name: zashboard
    image: ghcr.io/zephyruso/zashboard
    restart: always
    ports:
      - '80:80'

  # optional
  meta:
    container_name: meta
    image: docker.io/metacubex/mihomo:Alpha
    restart: always
    pid: host
    ipc: host
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - ./config.yaml:/root/.config/mihomo
      - /dev/net/tun:/dev/net/tun
 ```
