### ISSUE TITLE
通过url访问无法定位到正确的backend服务｜后端地址重复创建

### ISSUE THREAD

**Issue by gleechad** [Zephyruso/zashboard#283]
版本： [1.70.2]
操作系统： debian
部署：
```
services:
  zashboard:
    image: ghcr.io/zephyruso/zashboard:latest  # 镜像名称
    container_name: zashboard                 # 可选，指定容器名称
    ports:
      - "${ZASHBOARD_PORT}:80"                             # 主机端口:容器端口
    restart: unless-stopped                   # 可选，重启策略（类似 -d 的后台运行）
```

# 问题1: 
想要通过不同的url直接访问不同的后端服务，但是没能成功。 不是很确定是不是我的url写的有问题。每次进去还是最后一次选定的后端，因而总是需要手动选择下拉列表后界面才会刷新。例如：
http://board_ip:port/?hostname=ip1&port=9090&secret=123456#/proxies
http://board_ip:port/?hostname=ip2&port=9090&secret=123456#/proxies

# 问题2: 
后端下拉列表，直接点击右边的+号，会生成重复的后端地址。貌似在不重置浏览器记录的情况下，没办法维护。

谢谢
