### ISSUE TITLE
[bug]: v1.71.0 版本无法自动设置后端

### ISSUE THREAD

**Issue by muink** [Zephyruso/zashboard#285]
`v1.71.0` 版本无法自动设置后端, 会得到下图所示错误, 换回 `v1.70.2` 版本工作正常

这是后端设置 url:

`https://my.router.domain:4333/ui/#/setup?hostname=my.router.domain&port=4333&secret=5058fa5c-fa4a-4587-8da4-44e3b0e8e5c8`

这是 mihomo 部分配置:

``` yaml
tls:
  certificate: /etc/ssl/acme/my.router.domain.fullchain.crt
  private-key: /etc/ssl/acme/my.router.domain.key
external-controller-cors:
  allow-origins:
    - '*'
  allow-private-network: true
external-controller: '[::]:9090'
external-controller-tls: '[::]:4333'
secret: 5058fa5c-fa4a-4587-8da4-44e3b0e8e5c8
external-ui: /var/run/fchomo/ui
external-ui-url: https://codeload.github.com/zephyruso/zashboard/zip/refs/heads/gh-pages
```

主流的几个 Chromium 内核浏览器都测试过得到一样的结果:

![Image](https://github.com/user-attachments/assets/367defef-a787-41d4-a713-71029aa0aad3)
