### ISSUE TITLE
Issue with Proxy List Not Displaying in Zashboard

### ISSUE THREAD

**Issue by danuhdw** [Zephyruso/zashboard#311]
Hi,

I hope you're doing well. I wanted to let you know that I encountered an issue while using your Zashboard script. The list of proxy names fetched from the proxy provider does not appear to be displaying properly.

Could you please look into this and let me know if there’s a solution or if I need to provide more details to help troubleshoot?

Thank you for your time and effort in creating this script!

**Comment by Zephyruso** [comment]
> The list of proxy names fetched from the proxy provider does not appear to be displaying properly.

What is "does not appear to be displaying properly." Do you have a screenshot for that?

**Comment by danuhdw** [comment]
![Image](https://github.com/user-attachments/assets/7f88dd75-ea76-4ae8-9f6d-d4f3a4e41ec0)

To help explain the issue, I’ve attached a screenshot:

"wan-1" shows the proxy provider section in a collapsed state.

"wan-2" shows the same section expanded, but the proxy list is not visible.

**Comment by Zephyruso** [comment]
Does this issue only occur with this provider or all of the provider? Will it work correctly in the proxies? When you open the developer tools with F12, are there any errors? What are your system and browser versions?

**Comment by danuhdw** [comment]
This issue occurs with all providers. I believe there are no syntax errors in my configuration because the connection runs smoothly, and the proxy names appear successfully in the connection logs.

I am using the latest stable version of Windows 11 and the most recent version of Google Chrome. I’ve also attached a screenshot of the developer tools for your reference.

![Image](https://github.com/user-attachments/assets/e822184a-0ae9-43ef-ad20-64f5ca4e5e65)

**Comment by Zephyruso** [comment]
Can you paste your config to help me reproduce the issue? You can remove proxy node IPs, domains, and secret keys or password, but please keep fields like node names and icons.

**Comment by danuhdw** [comment]
config.yaml file
```yaml
# This option enables unified latency measurement for all proxies.
# When enabled, OpenClash will measure latency for all proxies simultaneously,
# reducing the time required for latency testing. This is useful for dual modem setups
# where latency consistency is critical.
unified-delay: true

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# RESTful web API listening address
# external-controller: 0.0.0.0:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
# external-ui: "/usr/share/openclash/ui"

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
secret: "SECRET"

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: true

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    # Option 1 | AdGuard DNS
    # - 94.140.14.14
    # - 94.140.15.15

    # Option 2 | Cloudflare DNS
    - 1.1.1.1
    - 1.0.0.1

    # Option 3 | Google DNS
    # - 8.8.8.8
    # - 8.8.4.4

  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    # Option 1 | AdGuard DNS
    # - 94.140.14.14
    # - 94.140.15.15
    # - https://dns.adguard-dns.com/dns-query
    # - tls://dns.adguard-dns.com

    # Option 2 | Cloudflare DNS
    - 1.1.1.1
    - 1.0.0.1
    - https://dns.cloudflare.com/dns-query
    - tls://1dot1dot1dot1.cloudflare-dns.com

    # Option 3 | Google DNS
    # - 8.8.8.8
    # - 8.8.4.4
    # - https://dns.google/dns-query
    # - tls://dns.google

proxy-providers:
  # Note: Recommended Healt Check URL
  # - https://cp.cloudflare.com
  # - https://www.gstatic.com/generate_204

  WAN-1:
    type: file
    path: "./proxy_provider/wan1.yaml"
    interval: 3600
    health-check:
      enable: true
      url: "https://cp.cloudflare.com"
      interval: 60
      timeout: 5000
      lazy: true
      expected-status: 204

  WAN-2:
    type: file
    path: "./proxy_provider/wan2.yaml"
    interval: 3600
    health-check:
      enable: true
      url: "https://cp.cloudflare.com"
      interval: 60
      timeout: 5000
      lazy: true
      expected-status: 204

proxy-groups:
  # Note: Healt Check
  # It will only check the proxies field of the proxy group,
  # and will not check the proxies of the proxy providers introduced through use.

  # MANUAL SELECT allows you to manually choose between WAN-1 and WAN-2.
  # Useful for testing or manual failover
  - name: MANUAL SELECT
    type: select
    use:
      - WAN-1
      - WAN-2

  # SPECIAL ACCESS is used for specific traffic that requires special handling,
  # such as blocking (REJECT) or fallback to another proxy.
  - name: SPECIAL ACCESS
    type: select
    proxies:
      - REJECT
      - BEST PING 1
      - BEST PING 2
      - FALLBACK
      - LOAD BALANCE
    # url: "https://cp.cloudflare.com"
    # interval: 60
    # lazy: true
    # timeout: 5000
    # max-failed-times: 5

  # BEST PING 1 and BEST PING 2 are used to select the fastest proxy from WAN-1 and WAN-2.
  # This is critical for dual modem setups to ensure optimal performance.
  - name: BEST PING 1
    type: url-test
    use:
      - WAN-1

  - name: BEST PING 2
    type: url-test
    use:
      - WAN-2

  # FALLBACK ensures traffic is routed to the next available proxy if the primary fails.
  - name: FALLBACK
    type: fallback
    proxies:
      - BEST PING 2
      - BEST PING 1
      - DIRECT
    # url: "https://cp.cloudflare.com"
    # interval: 60
    # lazy: true
    # timeout: 5000
    # max-failed-times: 5

  # LOAD BALANCE distributes traffic evenly across WAN-1 and WAN-2.
  - name: LOAD BALANCE
    type: load-balance
    use:
      - WAN-1
      - WAN-2
    strategy: consistent-hashing # or round-robin

rule-providers:
  # Ensure the YAML files exist in the specified paths.

  DIRECT:
    type: http
    path: "./rule_provider/direct.yaml"
    interval: 3600
    behavior: classical
    
  REJECT:
    type: http
    path: "./rule_provider/reject.yaml"
    url: "https://raw.githubusercontent.com/SOMETHING_HIDDEN/reject.yaml"
    interval: 3600
    behavior: classical

  Adult:
    type: http
    path: "./rule_provider/adult.yaml"
    url: "https://raw.githubusercontent.com/SOMETHING_HIDDEN/adult.yaml"
    interval: 3600
    behavior: classical

  Facebook:
    type: http
    path: "./rule_provider/facebook.yaml"
    url: "https://raw.githubusercontent.com/SOMETHING_HIDDEN/facebook.yaml"
    interval: 3600
    behavior: classical

  Games:
    type: http
    path: "./rule_provider/games.yaml"
    url: "https://raw.githubusercontent.com/SOMETHING_HIDDEN/games.yaml"
    interval: 3600
    behavior: classical

  Instagram:
    type: http
    path: "./rule_provider/instagram.yaml"
    url: "https://raw.githubusercontent.com/SOMETHING_HIDDEN/instagram.yaml"
    interval: 3600
    behavior: classical

  TikTok:
    type: http
    path: "./rule_provider/tiktok.yaml"
    url: "https://raw.githubusercontent.com/SOMETHING_HIDDEN/tiktok.yaml"
    interval: 3600
    behavior: classical

  Twitter:
    type: http
    path: "./rule_provider/twitter.yaml"
    url: "https://raw.githubusercontent.com/SOMETHING_HIDDEN/twitter.yaml"
    interval: 3600
    behavior: classical

  WhatsApp:
    type: http
    path: "./rule_provider/whatsapp.yaml"
    url: "https://raw.githubusercontent.com/SOMETHING_HIDDEN/whatsapp.yaml"
    interval: 3600
    behavior: classical

  YouTube:
    type: http
    path: "./rule_provider/youtube.yaml"
    url: "https://raw.githubusercontent.com/SOMETHING_HIDDEN/youtube.yaml"
    interval: 3600
    behavior: classical

rules:
  # Block unwanted traffic using the REJECT rule.
  - RULE-SET,REJECT,REJECT

  # Direct traffic for local or priority services.
  - RULE-SET,DIRECT,DIRECT
  - RULE-SET,Games,DIRECT
  - RULE-SET,WhatsApp,DIRECT

  # Route adult content through SPECIAL ACCESS.
  - RULE-SET,Adult,SPECIAL ACCESS

  # Route social media and streaming traffic through GLOBAL (VPN Tunnel).
  - RULE-SET,Facebook,GLOBAL
  - RULE-SET,Instagram,GLOBAL
  - RULE-SET,TikTok,GLOBAL
  - RULE-SET,Twitter,GLOBAL
  - RULE-SET,YouTube,GLOBAL

  # Match all other traffic and route through GLOBAL.
  - MATCH,GLOBAL
```

**Comment by danuhdw** [comment]
wan1.yaml (proxy provider file)
```yaml
# Define anchors for common configurations
common: &common
  type: trojan
  server: SERVER
  port: 443
  password: PASSWORD # Default password, can be overridden in each proxy
  udp: true
  skip-cert-verify: true
  network: ws
  interface-name: eth1 # Specify the network interface to use

# Define anchor for ws-opts configuration
ws_opts: &ws_opts
  path: /trojan # Default path, can be overridden in each proxy

proxies:

  # NetQ
  - name: "N-ID1 Reguler"
    <<: *common
    # password: override_default_password
    sni: id1.HOST-HIDDEN.com
    ws-opts:
      <<: *ws_opts
      # path: "/override_default_path"
      headers:
        Host: id1.HOST-HIDDEN.com

  # NetQ
  - name: "N-ID2 Reguler"
    <<: *common
    # password: override_default_password
    sni: id2.HOST-HIDDEN.com
    ws-opts:
      <<: *ws_opts
      # path: "/override_default_path"
      headers:
        Host: id2.HOST-HIDDEN.com

  # NetQ
  - name: "N-ID3 Reguler"
    <<: *common
    # password: override_default_password
    sni: id3.HOST-HIDDEN.com
    ws-opts:
      <<: *ws_opts
      # path: "/override_default_path"
      headers:
        Host: id3.HOST-HIDDEN.com
```

**Comment by Zephyruso** [comment]
Does the online version of zashboard works now? I have made some fix

**Comment by danuhdw** [comment]
Thank you for the update! I just tested the updated version of Zashboard, but it seems like the issue is still persisting. The proxy list is still not displaying as expected.

**Comment by Zephyruso** [comment]
Could you paste the wan-2.yaml like wan-1and  give me a screenshot of click this part if this error still persisting in  F12 console 

![Image](https://github.com/user-attachments/assets/d29c2e52-d313-426c-8101-28275f266a70)

**Comment by danuhdw** [comment]
wan2.yaml (proxy provider file)
```yaml
# Define anchors for common configurations
common: &common
  type: trojan
  server: SERVER
  port: 443
  password: PASSWORD # Default password, can be overridden in each proxy
  udp: true
  skip-cert-verify: true
  network: ws
  interface-name: wwan0 # Specify the network interface to use

# Define anchor for ws-opts configuration
ws_opts: &ws_opts
  path: /trojan # Default path, can be overridden in each proxy

proxies:

  # NetQ
  - name: "N-ID1"
    <<: *common
    # password: override_default_password
    sni: id1.HOST-HIDDEN.com
    ws-opts:
      <<: *ws_opts
      # path: "/override_default_path"
      headers:
        Host: id1.HOST-HIDDEN.com

  # NetQ
  - name: "N-ID2"
    <<: *common
    # password: override_default_password
    sni: id2.HOST-HIDDEN.id1.HOST-HIDDEN.com
    ws-opts:
      <<: *ws_opts
      # path: "/override_default_path"
      headers:
        Host: id2.HOST-HIDDEN.id1.HOST-HIDDEN.com

  # NetQ
  - name: "N-ID3"
    <<: *common
    # password: override_default_password
    sni: id3.HOST-HIDDEN.id1.HOST-HIDDEN.com
    ws-opts:
      <<: *ws_opts
      # path: "/override_default_path"
      headers:
        Host: id3.HOST-HIDDEN.id1.HOST-HIDDEN.com
```
