### ISSUE TITLE
策略组没有按照配置文件中的顺序排序

### ISSUE THREAD

**Issue by rumianoesa** [Zephyruso/zashboard#329]
```
proxy-groups:
  - name: Bilibili
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: OpenAI
    type: fallback
    url: https://cp.cloudflare.com/generate_204
    interval: 86400
    proxies:
      - 🇸🇬
      - 🇯🇵
  - name: PROXY
    type: fallback
    url: https://www.gstatic.com/generate_204
    interval: 86400
    proxies:
      - 🇭🇰
      - 🇹🇼
      - 🇸🇬
      - 🇯🇵
  - name: PROXYIP
    type: fallback
    url: https://cp.cloudflare.com/generate_204
    interval: 86400
    proxies:
      - 🇭🇰
      - 🇹🇼
      - 🇸🇬
      - 🇯🇵
  - name: GLOBAL
    type: select
    proxies:
      - PROXY
      - DIRECT
    hidden: true
```

比如以这四个name为例，PROXYIP会在webui中排在PROXY的前面
