### ISSUE TITLE
在规则页面 geoip 规则显示规则数量为 0

### ISSUE THREAD

**Issue by 63936** [Zephyruso/zashboard#346]
在规则页面 geosite，ruleset 规则都能显示具体的规则数量，但是 geoip 显示的规则数量为 0。

使用的版本是 1.80.1

mihomo 版本 alpha-76052b5

```
geo-auto-update: true
geo-update-interval: 24

geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
```

![Image](https://github.com/user-attachments/assets/44c6b8a8-cec9-4711-bf4f-7caa184913bd)
