### ISSUE TITLE
开启独立延迟测试后，代理提供商处测速无响应

### ISSUE THREAD

**Issue by mengrank** [Zephyruso/zashboard#384]
## Bug 报告

**zashboard版本:**
- 版本: 1.89.2
- 
**系统版本:**
- 操作系统: Windows 10
- 版本: 19045.5487
- 
**浏览器版本:**
- 浏览器: Thorium
- 版本: 130.0.6723.174

**复现步骤:**
1. 开启独立延迟测试
2. 在代理提供商界面点击测速按钮

**预期行为:**
- 对应代理组更新延迟

**实际行为:**
- 无响应

**Bug 截图:**

![Image](https://github.com/user-attachments/assets/e22d7972-cfd1-4888-bc09-c3eb03fb0f06)

)

**附加信息:**
- 点击1处无法更新对应延迟，只有点击2处才会出现延迟

- 配置文件如下：
 节点配置
NodeParam: &NodeParam {type: http, interval: 86400, health-check: {enable: true, url: 'http://cp.cloudflare.com', interval: 300}}
 节点订阅
proxy-providers: 
  xxxx:
    url: 'xxxxx'
    <<: *NodeParam
    path: './proxy_provider/providers1.yaml'

预期会根据配置内的url进行测速
---

**Comment by mengrank** [comment]
补充全配置
```
### 节点配置
NodeParam: &NodeParam {type: http, interval: 86400, health-check: {enable: true, url: 'http://cp.cloudflare.com', interval: 300}}
# 节点订阅
proxy-providers: 

  xxxx:
     url: 'xxxxxxxx'
     <<: *NodeParam
     path: './proxy_provider/providers1.yaml'  


# 节点筛选
FilterHK: &FilterHK '^(?=.*(香港|HK|Hong|🇭🇰))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点)).*$'
FilterJP: &FilterJP '^(?=.*(日本|JP|Japan|🇯🇵))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点)).*$'
FilterKR: &FilterKR '^(?=.*(韩国|韓|KR|Korea|🇰🇷))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点)).*$'
FilterSG: &FilterSG '^(?=.*(新加坡|狮城|SG|Singapore|🇸🇬))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点)).*$'
FilterUS: &FilterUS '^(?=.*(美国|US|United States|America|🇺🇸))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点)).*$'
FilterUK: &FilterUK '^(?=.*(英国|UK|United Kingdom|🇬🇧))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点)).*$'
FilterFR: &FilterFR '^(?=.*(法国|FR|France|🇫🇷))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点)).*$'
FilterDE: &FilterDE '^(?=.*(德国|DE|Germany|🇩🇪))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点)).*$'
FilterTW: &FilterTW '^(?=.*(台湾|TW|Taiwan|Wan|🇹🇼|🇨🇳))^(?!.*(网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点)).*$'
FilterOthers: &FilterOthers '^(?!.*(🇭🇰|HK|Hong|香港|🇹🇼|TW|Taiwan|Wan|🇯🇵|JP|Japan|日本|🇸🇬|SG|Singapore|狮城|🇺🇸|US|United States|America|美国|🇩🇪|DE|Germany|德国|🇬🇧|UK|United Kingdom|英国|🇰🇷|KR|Korea|韩国|韓|🇫🇷|FR|France|法国)).*$'
FilterAll: &FilterAll '^(?=.*(.))(?!.*((?i)群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|(\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author)\b|(\d{4}-\d{2}-\d{2}|\d+G)))).*$'

Select: &Select {type: select, url: 'http://cp.cloudflare.com', disable-udp: false, hidden: false, include-all: true}
Auto: &Auto {type: url-test, url: 'http://www.google.com/generate_204', interval: 300, tolerance: 50, disable-udp: false, hidden: true, include-all: true}

# 策略组

proxy-groups: 
  - {name: 节点选择, type: select, proxies: [自动选择, 手动选择, 所有节点, DIRECT], url: https://cp.cloudflare.com, icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Static.png}
  - {name: 手动选择, type: select, proxies: [🇭🇰 - 手动选择, 🇯🇵 - 手动选择, 🇰🇷 - 手动选择, 🇸🇬 - 手动选择, 🇺🇸 - 手动选择, 🇬🇧 - 手动选择, 🇫🇷 - 手动选择, 🇩🇪 - 手动选择, 🇹🇼 - 手动选择, Others - 手动选择], url: https://cp.cloudflare.com, icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Select.png}
  - {name: 自动选择, type: select, proxies: [🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择, AllIn - 自动选择], url: https://cp.cloudflare.com, icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Auto_Speed.png}
  - {name: Telegram, type: select, proxies: [节点选择, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Telegram.png}
  - {name: AI, type: select, proxies: [🇺🇸 - 自动选择, 节点选择, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/OpenAI.png}
  - {name: 苹果服务, type: select, proxies: [DIRECT, 节点选择, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Apple.png}
  - {name: 微软服务, type: select, proxies: [DIRECT, 节点选择, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Microsoft.png}
  - {name: Emby,type: select, proxies: [DIRECT, 节点选择, 🇭🇰 - 手动选择, 🇰🇷 - 手动选择, 🇸🇬 - 手动选择, 🇺🇸 - 手动选择, 🇬🇧 - 手动选择, 🇫🇷 - 手动选择, 🇩🇪 - 手动选择, 🇹🇼 - 手动选择], icon: https://github.mengxianying740.workers.dev/https://raw.githubusercontent.com/mengrank/mengrankgo/refs/heads/master/openclash/emby.png}
  - {name: YouTube&X,type: select, proxies: [节点选择, DIRECT, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/YouTube.png}
  - {name: GitHub,type: select, proxies: [节点选择, DIRECT, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/GitHub.png}
  - {name: 谷歌服务,type: select, proxies: [节点选择, DIRECT, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Google_Suite/Google.png}
  - {name: 游戏平台,type: select, proxies: [DIRECT, 节点选择, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://github.mengxianying740.workers.dev/https://raw.githubusercontent.com/mengrank/mengrankgo/refs/heads/master/openclash/game.png}
  - {name: 国外媒体,type: select, proxies: [节点选择, DIRECT, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Amazon.png}
  - {name: 谷歌FCM,type: select, proxies: [DIRECT, 节点选择, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Google_Suite/PlayStore.png}
  - {name: Steam,type: select, proxies: [DIRECT, 节点选择, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Steam.png}
  - {name: 测速工具,type: select, proxies: [DIRECT, 节点选择, 🇭🇰 - 自动选择, 🇯🇵 - 自动选择, 🇰🇷 - 自动选择, 🇸🇬 - 自动选择, 🇺🇸 - 自动选择, 🇬🇧 - 自动选择, 🇫🇷 - 自动选择, 🇩🇪 - 自动选择, 🇹🇼 - 自动选择], icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Speedtest.png}
  - {name: 全球直连,type: select, proxies: [DIRECT] ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/ReverbNation.png}
  

  
  # 自动选择
  - {name: 🇭🇰 - 自动选择, <<: *Auto, filter: *FilterHK}
  - {name: 🇯🇵 - 自动选择, <<: *Auto, filter: *FilterJP}
  - {name: 🇰🇷 - 自动选择, <<: *Auto, filter: *FilterKR}
  - {name: 🇸🇬 - 自动选择, <<: *Auto, filter: *FilterSG}
  - {name: 🇺🇸 - 自动选择, <<: *Auto, filter: *FilterUS}
  - {name: 🇬🇧 - 自动选择, <<: *Auto, filter: *FilterUK}
  - {name: 🇫🇷 - 自动选择, <<: *Auto, filter: *FilterFR}
  - {name: 🇩🇪 - 自动选择, <<: *Auto, filter: *FilterDE}
  - {name: 🇹🇼 - 自动选择, <<: *Auto, filter: *FilterTW}

  # 手动选择
  - {name: 🇭🇰 - 手动选择, <<: *Select, filter: *FilterHK ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/Hong_Kong.png}
  - {name: 🇯🇵 - 手动选择, <<: *Select, filter: *FilterJP ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/Japan.png}
  - {name: 🇰🇷 - 手动选择, <<: *Select, filter: *FilterKR ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/South_Korea.png}
  - {name: 🇸🇬 - 手动选择, <<: *Select, filter: *FilterSG ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/Singapore.png}
  - {name: 🇺🇸 - 手动选择, <<: *Select, filter: *FilterUS ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/United_States.png}
  - {name: 🇬🇧 - 手动选择, <<: *Select, filter: *FilterUK ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/United_Kingdom.png}
  - {name: 🇫🇷 - 手动选择, <<: *Select, filter: *FilterFR ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/France.png}
  - {name: 🇩🇪 - 手动选择, <<: *Select, filter: *FilterDE ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/Germany.png}
  - {name: 🇹🇼 - 手动选择, <<: *Select, filter: *FilterTW ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/Taiwan.png}
  - {name: Others - 手动选择, <<: *Select, filter: *FilterOthers ,icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Streaming.png}

  # 全部节点
  #- {name: AllIn - 手动选择, <<: *Select, filter: *FilterAll}
  - {name: AllIn - 自动选择, <<: *Auto, filter: *FilterAll}
```
